# Generated by Django 4.2.11 on 2026-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_add_loja_isolation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
