# Generated by Django 5.0.1 on 2026-01-15 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_produtos', models.IntegerField(default=100)),
                ('max_usuarios', models.IntegerField(default=5)),
                ('max_pedidos_mes', models.IntegerField(default=1000)),
                ('espaco_storage_gb', models.IntegerField(default=5)),
                ('tem_relatorios_avancados', models.BooleanField(default=False)),
                ('tem_api_acesso', models.BooleanField(default=False)),
                ('tem_suporte_prioritario', models.BooleanField(default=False)),
                ('tem_dominio_customizado', models.BooleanField(default=False)),
                ('tem_whatsapp_integration', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['ordem', 'preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='TipoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('dashboard_template', models.CharField(default='default', max_length=50)),
                ('cor_primaria', models.CharField(default='#10B981', max_length=7)),
                ('cor_secundaria', models.CharField(default='#059669', max_length=7)),
                ('logo_padrao', models.URLField(blank=True)),
                ('tem_produtos', models.BooleanField(default=True)),
                ('tem_servicos', models.BooleanField(default=False)),
                ('tem_agendamento', models.BooleanField(default=False)),
                ('tem_delivery', models.BooleanField(default=False)),
                ('tem_estoque', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Loja',
                'verbose_name_plural': 'Tipos de Loja',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('database_name', models.CharField(max_length=100, unique=True)),
                ('database_created', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True)),
                ('cor_primaria', models.CharField(blank=True, max_length=7)),
                ('cor_secundaria', models.CharField(blank=True, max_length=7)),
                ('dominio_customizado', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('login_page_url', models.CharField(blank=True, max_length=255)),
                ('login_background', models.URLField(blank=True)),
                ('login_logo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_owned', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='superadmin.planoassinatura')),
                ('tipo_loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='superadmin.tipoloja')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_proxima_cobranca', models.DateField()),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.IntegerField(default=10)),
                ('status_pagamento', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pagamento Pendente'), ('atrasado', 'Atrasado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('ultimo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='superadmin.loja')),
            ],
            options={
                'verbose_name': 'Financeiro da Loja',
                'verbose_name_plural': 'Financeiros das Lojas',
            },
        ),
        migrations.CreateModel(
            name='PagamentoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_mes', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('comprovante', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='superadmin.financeiroloja')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='superadmin.loja')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('superadmin', 'Super Admin'), ('suporte', 'Suporte')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto', models.URLField(blank=True)),
                ('pode_criar_lojas', models.BooleanField(default=False)),
                ('pode_gerenciar_financeiro', models.BooleanField(default=False)),
                ('pode_acessar_todas_lojas', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lojas_acesso', models.ManyToManyField(blank=True, related_name='usuarios_suporte', to='superadmin.loja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário do Sistema',
                'verbose_name_plural': 'Usuários do Sistema',
            },
        ),
    ]
