# Generated by Django 5.0.1 on 2026-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_planoassinatura_tipos_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='senha_provisoria',
            field=models.CharField(blank=True, help_text='Senha provisória gerada automaticamente', max_length=50),
        ),
    ]
