# Generated by Django 4.2.11 on 2026-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiroloja',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no Asaas', max_length=100),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='asaas_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento atual no Asaas', max_length=100),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='boleto_pdf_url',
            field=models.URLField(blank=True, help_text='URL do PDF do boleto'),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='boleto_url',
            field=models.URLField(blank=True, help_text='URL do boleto no Asaas'),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='pix_copy_paste',
            field=models.TextField(blank=True, help_text='PIX Copia e Cola'),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='pix_qr_code',
            field=models.TextField(blank=True, help_text='QR Code PIX'),
        ),
        migrations.AddField(
            model_name='pagamentoloja',
            name='asaas_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento no Asaas', max_length=100),
        ),
        migrations.AddField(
            model_name='pagamentoloja',
            name='boleto_pdf_url',
            field=models.URLField(blank=True, help_text='URL do PDF do boleto'),
        ),
        migrations.AddField(
            model_name='pagamentoloja',
            name='boleto_url',
            field=models.URLField(blank=True, help_text='URL do boleto'),
        ),
        migrations.AddField(
            model_name='pagamentoloja',
            name='pix_copy_paste',
            field=models.TextField(blank=True, help_text='PIX Copia e Cola'),
        ),
        migrations.AddField(
            model_name='pagamentoloja',
            name='pix_qr_code',
            field=models.TextField(blank=True, help_text='QR Code PIX'),
        ),
        migrations.AddIndex(
            model_name='financeiroloja',
            index=models.Index(fields=['asaas_customer_id'], name='fin_asaas_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='financeiroloja',
            index=models.Index(fields=['asaas_payment_id'], name='fin_asaas_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoloja',
            index=models.Index(fields=['asaas_payment_id'], name='pag_asaas_payment_idx'),
        ),
    ]
