# Generated by Django 4.2.11 on 2026-01-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_usersession'),
        ('superadmin', '0009_add_sync_and_block_fields'),
    ]

    operations = [
    ]
