# Generated by Django 4.2.11 on 2026-01-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_merge_0002_usersession_0009_add_sync_and_block_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_user_id_2ad246_idx',
            old_name='user_sessio_user_id_b8e9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_last_ac_7cb421_idx',
            old_name='user_sessio_last_ac_c4f8d2_idx',
        ),
    ]
