# Generated by Django 4.2.11 on 2026-02-09 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0013_historicoacessoglobal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolacaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso_cross_tenant', 'Acesso Cross-Tenant'), ('brute_force', 'Tentativa de Brute Force'), ('rate_limit_exceeded', 'Rate Limit Excedido'), ('privilege_escalation', 'Escalação de Privilégios'), ('mass_deletion', 'Exclusão em Massa'), ('ip_change', 'Mudança de IP'), ('suspicious_pattern', 'Padrão Suspeito')], db_index=True, help_text='Tipo de violação detectada', max_length=50)),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, help_text='Nível de criticidade da violação', max_length=20)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('investigando', 'Investigando'), ('resolvida', 'Resolvida'), ('falso_positivo', 'Falso Positivo')], db_index=True, default='nova', help_text='Status da investigação', max_length=20)),
                ('usuario_email', models.EmailField(help_text='Email do usuário (backup)', max_length=254)),
                ('usuario_nome', models.CharField(help_text='Nome do usuário', max_length=200)),
                ('loja_nome', models.CharField(blank=True, help_text='Nome da loja (backup)', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição da violação detectada')),
                ('detalhes_tecnicos', models.JSONField(default=dict, help_text='Detalhes técnicos adicionais (JSON)')),
                ('ip_address', models.GenericIPAddressField(help_text='IP de origem da violação')),
                ('resolvido_em', models.DateTimeField(blank=True, help_text='Data/hora da resolução', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre investigação e resolução')),
                ('notificado', models.BooleanField(default=False, help_text='Indica se SuperAdmin foi notificado')),
                ('notificado_em', models.DateTimeField(blank=True, help_text='Data/hora da notificação', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logs_relacionados', models.ManyToManyField(blank=True, help_text='Logs que evidenciam a violação', related_name='violacoes', to='superadmin.historicoacessoglobal')),
                ('loja', models.ForeignKey(blank=True, help_text='Loja onde ocorreu a violação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violacoes_seguranca', to='superadmin.loja')),
                ('resolvido_por', models.ForeignKey(blank=True, help_text='SuperAdmin que resolveu a violação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violacoes_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que cometeu a violação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violacoes_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Violação de Segurança',
                'verbose_name_plural': 'Violações de Segurança',
                'db_table': 'superadmin_violacoes_seguranca',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'criticidade', '-created_at'], name='viol_status_crit_idx'), models.Index(fields=['tipo', '-created_at'], name='viol_tipo_date_idx'), models.Index(fields=['user', '-created_at'], name='viol_user_date_idx'), models.Index(fields=['loja', '-created_at'], name='viol_loja_date_idx'), models.Index(fields=['ip_address', '-created_at'], name='viol_ip_date_idx'), models.Index(fields=['notificado', 'criticidade'], name='viol_notif_crit_idx')],
            },
        ),
    ]
