# Generated by Django 4.2.11 on 2026-02-20 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0018_add_owner_telefone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profissionalusuario',
            name='superadmin_profissionalusuario_user_loja_uniq',
        ),
        migrations.AlterField(
            model_name='profissionalusuario',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('profissional', 'Profissional (só agenda e bloqueios próprios)'), ('recepcao', 'Recepção (acesso completo)'), ('recepcionista', 'Recepcionista'), ('caixa', 'Caixa'), ('limpeza', 'Limpeza'), ('estoque', 'Estoque')], default='profissional', help_text='Tipo de acesso: administrador, profissional, recepcionista, caixa, limpeza, estoque.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='profissionalusuario',
            unique_together={('user', 'loja')},
        ),
    ]
