# Generated by Django 4.2.11 on 2026-02-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_mercadopago_config_chave_pix_estatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiroloja',
            name='data_envio_senha',
            field=models.DateTimeField(blank=True, help_text='Data e hora do envio da senha provisória', null=True),
        ),
        migrations.AddField(
            model_name='financeiroloja',
            name='senha_enviada',
            field=models.BooleanField(default=False, help_text='Indica se a senha provisória já foi enviada'),
        ),
        migrations.AlterField(
            model_name='financeiroloja',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento boleto no Mercado Pago', max_length=100),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='chave_pix_estatica',
            field=models.CharField(blank=True, help_text='Chave PIX (copia e cola) exibida na página do boleto quando não houver PIX dinâmico do Mercado Pago. Ex.: chave aleatória para pagamento manual.', max_length=120, verbose_name='Chave PIX estática (fallback)'),
        ),
        migrations.AlterField(
            model_name='pagamentoloja',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento boleto no Mercado Pago', max_length=100),
        ),
        migrations.CreateModel(
            name='EmailRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(help_text='Email do destinatário', max_length=254)),
                ('assunto', models.CharField(help_text='Assunto do email', max_length=255)),
                ('mensagem', models.TextField(help_text='Corpo do email')),
                ('tentativas', models.IntegerField(default=0, help_text='Número de tentativas realizadas')),
                ('max_tentativas', models.IntegerField(default=3, help_text='Número máximo de tentativas')),
                ('enviado', models.BooleanField(default=False, help_text='Indica se o email foi enviado com sucesso')),
                ('erro', models.TextField(blank=True, help_text='Último erro ocorrido ao tentar enviar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('proxima_tentativa', models.DateTimeField(blank=True, help_text='Data e hora da próxima tentativa de envio', null=True)),
                ('loja', models.ForeignKey(blank=True, help_text='Loja relacionada ao email (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_retry', to='superadmin.loja')),
            ],
            options={
                'verbose_name': 'Email para Retry',
                'verbose_name_plural': 'Emails para Retry',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['enviado', 'tentativas'], name='email_retry_status_idx'),
                    models.Index(fields=['proxima_tentativa'], name='email_retry_proxima_idx'),
                    models.Index(fields=['loja', 'enviado'], name='email_retry_loja_idx'),
                ],
            },
        ),
    ]
