# Generated by Django 4.2.11 on 2026-03-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0029_remove_trial_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoloja',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de App', 'verbose_name_plural': 'Tipos de App'},
        ),
        migrations.CreateModel(
            name='HistoricoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], db_index=True, help_text='Tipo de backup: manual ou automático', max_length=20)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], db_index=True, default='processando', help_text='Status atual do processamento do backup', max_length=20)),
                ('arquivo_nome', models.CharField(help_text='Nome do arquivo de backup gerado', max_length=255)),
                ('arquivo_tamanho_mb', models.DecimalField(decimal_places=2, default=0, help_text='Tamanho do arquivo em megabytes', max_digits=10)),
                ('arquivo_path', models.CharField(blank=True, help_text='Caminho do arquivo no storage (S3, filesystem, etc)', max_length=500)),
                ('total_registros', models.IntegerField(default=0, help_text='Total de registros incluídos no backup')),
                ('tabelas_incluidas', models.JSONField(default=dict, help_text='Dicionário com contagem de registros por tabela')),
                ('tempo_processamento_segundos', models.IntegerField(blank=True, help_text='Tempo total de processamento em segundos', null=True)),
                ('erro_mensagem', models.TextField(blank=True, help_text='Mensagem de erro detalhada (se houver)')),
                ('email_enviado', models.BooleanField(default=False, help_text='Indica se o backup foi enviado por email')),
                ('email_enviado_em', models.DateTimeField(blank=True, help_text='Data e hora do envio do email', null=True)),
                ('email_destinatario', models.EmailField(blank=True, help_text='Email do destinatário', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora de criação do registro')),
                ('concluido_em', models.DateTimeField(blank=True, help_text='Data e hora de conclusão do backup', null=True)),
                ('loja', models.ForeignKey(help_text='Loja que teve backup realizado', on_delete=django.db.models.deletion.CASCADE, related_name='historico_backups', to='superadmin.loja')),
                ('solicitado_por', models.ForeignKey(blank=True, help_text='Usuário que solicitou o backup (para backups manuais)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Histórico de Backups',
                'db_table': 'superadmin_historico_backup',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loja', '-created_at'], name='hist_backup_loja_idx'), models.Index(fields=['status', '-created_at'], name='hist_backup_status_idx'), models.Index(fields=['tipo', '-created_at'], name='hist_backup_tipo_idx'), models.Index(fields=['email_enviado'], name='hist_backup_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_automatico_ativo', models.BooleanField(default=False, help_text='Ativa ou desativa o backup automático')),
                ('horario_envio', models.TimeField(default='03:00:00', help_text='Horário para envio automático do backup (formato 24h)')),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='semanal', help_text='Frequência de execução do backup automático', max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana para backup semanal (0=Segunda, 6=Domingo)', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Dia do mês para backup mensal (1-28)', null=True)),
                ('ultimo_backup', models.DateTimeField(blank=True, help_text='Data e hora do último backup realizado', null=True)),
                ('ultimo_envio_email', models.DateTimeField(blank=True, help_text='Data e hora do último envio de email com backup', null=True)),
                ('total_backups_realizados', models.IntegerField(default=0, help_text='Contador total de backups realizados')),
                ('incluir_imagens', models.BooleanField(default=False, help_text='Incluir imagens no backup (aumenta significativamente o tamanho)')),
                ('manter_ultimos_n_backups', models.IntegerField(default=5, help_text='Quantidade de backups a manter armazenados no servidor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(help_text='Loja associada a esta configuração', on_delete=django.db.models.deletion.CASCADE, related_name='config_backup', to='superadmin.loja')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
                'db_table': 'superadmin_configuracao_backup',
                'indexes': [models.Index(fields=['backup_automatico_ativo', 'horario_envio'], name='cfg_backup_ativo_idx'), models.Index(fields=['ultimo_backup'], name='cfg_backup_ultimo_idx')],
            },
        ),
    ]
