# Generated by Django 4.2.11 on 2026-04-13 00:35
#
# 0004_add_imagem_fields já pode ter criado essas colunas via SQL no Postgres;
# esta migração alinha o estado do Django sem falhar se a coluna já existir.

from django.db import migrations, models


TABLES = (
    ('homepage_funcionalidade', 'funcionalidade'),
    ('homepage_modulo_sistema', 'modulosistema'),
)


def _column_exists(cursor, vendor, table: str) -> bool:
    if vendor == 'postgresql':
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = %s AND column_name = 'imagem'
            """,
            [table],
        )
        return cursor.fetchone() is not None
    if vendor == 'sqlite':
        cursor.execute(f'PRAGMA table_info({table})')
        return any(row[1] == 'imagem' for row in cursor.fetchall())
    return False


def add_imagem_columns_if_missing(apps, schema_editor):
    from django.db import connection

    vendor = connection.vendor
    with connection.cursor() as cursor:
        for table, _label in TABLES:
            if _column_exists(cursor, vendor, table):
                continue
            if vendor == 'sqlite':
                cursor.execute(
                    f'ALTER TABLE {table} ADD COLUMN imagem varchar(500) NULL'
                )
            else:
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN imagem VARCHAR(500) NULL'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_remove_herosection_imagem'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='funcionalidade',
                    name='imagem',
                    field=models.URLField(
                        blank=True,
                        help_text='URL da imagem da funcionalidade (opcional, substitui ícone)',
                        max_length=500,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name='modulosistema',
                    name='imagem',
                    field=models.URLField(
                        blank=True,
                        help_text='URL da imagem do módulo (opcional, substitui ícone)',
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_imagem_columns_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
