services:
  # Backend Python/Django - Servidor Backup
  - type: web
    name: lwksistemas-backup
    env: python
    region: oregon
    plan: free
    branch: master
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /api/superadmin/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.12
      - key: ALLOWED_HOSTS
        value: .onrender.com,lwksistemas-38ad47519238.herokuapp.com,lwksistemas.herokuapp.com,lwksistemas.com.br
      - key: ASAAS_API_KEY
        value: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjY5ZjZhMmI3LTFmZWYtNDdkMC1iMmVkLTY4NWU0NzkxMmJlZDo6$aach_86202caf-f697-49c8-b95b-bdf23c45dbd8
      - key: ASAAS_INTEGRATION_ENABLED
        value: true
      - key: ASAAS_SANDBOX
        value: true
      - key: CONN_MAX_AGE
        value: 60
      - key: CORS_ORIGINS
        value: https://lwksistemas.com.br,https://www.lwksistemas.com.br,https://frontend-r3q0a1lw4-lwks-projects-48afd555.vercel.app,https://frontend-7v1dtxf44-lwks-projects-48afd555.vercel.app
      - key: DATABASE_URL
        value: postgres://uav89ndofshapp:p3e1961bd3950804921290cace7a9cfda23395a9450b6b52273b5180c93dc5c7b@cet8r1hlj0mlnt.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d6rgsibf3ofk9d
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_production
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: cabbshvjjbcjagzh
      - key: EMAIL_HOST_USER
        value: lwksistemas@gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: REDIS_URL
        value: rediss://:p4e1eb26897f7bd54b09923045e224c76d12f1f2a35724fe97fffeee7264d9081@ec2-18-232-249-224.compute-1.amazonaws.com:19140
      - key: SECRET_KEY
        value: django-insecure-prod-a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
      - key: SECURITY_NOTIFICATION_EMAILS
        value: admin@lwksistemas.com.br,seguranca@lwksistemas.com.br
      - key: SITE_URL
        value: https://lwksistemas.com.br
      - key: USE_REDIS
        value: false
