# Generated by Django 4.2.11 on 2026-04-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('tipo', models.CharField(choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('enxoval', 'Enxoval'), ('outros', 'Outros')], default='limpeza', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('prioridade', models.IntegerField(default=2, help_text='1=alta, 2=média, 3=baixa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hotel_governanca_tarefas',
                'ordering': ['status', 'prioridade', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, default='', max_length=30)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_hospedes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('numero', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, default='', help_text='Ex.: Suíte 203', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', help_text='Ex.: Standard, Luxo', max_length=80)),
                ('capacidade', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_quartos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_quarto', models.CharField(blank=True, default='', max_length=80)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_tarifas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['loja_id', 'is_active'], name='hotel_tarifa_loja_act_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('adultos', models.IntegerField(default=2)),
                ('criancas', models.IntegerField(default=0)),
                ('canal', models.CharField(blank=True, default='', help_text='Ex.: Direto, Booking, Expedia', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('cancelada', 'Cancelada'), ('no_show', 'No-show')], default='pendente', max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.quarto')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='hotel.tarifa')),
            ],
            options={
                'db_table': 'hotel_reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quarto',
            index=models.Index(fields=['loja_id', 'status'], name='hotel_quarto_loja_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quarto',
            index=models.Index(fields=['loja_id', 'is_active'], name='hotel_quarto_loja_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='quarto',
            constraint=models.UniqueConstraint(fields=('loja_id', 'numero'), name='hotel_quarto_loja_numero_uniq'),
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['loja_id', 'is_active'], name='hotel_hosp_loja_act_idx'),
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['loja_id', 'documento'], name='hotel_hosp_loja_doc_idx'),
        ),
        migrations.AddField(
            model_name='governancatarefa',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_governanca', to='hotel.quarto'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['loja_id', 'status'], name='hotel_reserva_loja_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['loja_id', 'data_checkin'], name='hotel_reserva_loja_in_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['loja_id', 'data_checkout'], name='hotel_reserva_loja_out_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['loja_id', 'is_active'], name='hotel_reserva_loja_act_idx'),
        ),
        migrations.AddIndex(
            model_name='governancatarefa',
            index=models.Index(fields=['loja_id', 'status'], name='hotel_gov_loja_status_idx'),
        ),
        migrations.AddIndex(
            model_name='governancatarefa',
            index=models.Index(fields=['loja_id', 'tipo'], name='hotel_gov_loja_tipo_idx'),
        ),
    ]
