# Generated by Django 4.2.11 on 2026-04-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_add_assinatura_digital_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaassinatura',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='reservatemplate',
            name='is_padrao',
            field=models.BooleanField(default=False, help_text='Template padrão para novas confirmações'),
        ),
        migrations.AlterField(
            model_name='reservatemplate',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
