# Generated by Django 4.2.11 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_configuracaohotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaohotel',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status_assinatura',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_hospede', 'Aguardando Hóspede'), ('aguardando_funcionario', 'Aguardando Funcionário'), ('concluido', 'Concluído'), ('manual', 'Assinado Manualmente')], default='rascunho', max_length=25),
        ),
    ]
