# Generated by Django 4.2.11 on 2026-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_integration', '0002_nfse_asaas_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfse',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
