# Generated by Django 4.2.11 on 2026-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('agendamento', 'Agendamento'), ('cancelamento', 'Cancelamento'), ('lembrete', 'Lembrete'), ('financeiro', 'Financeiro'), ('tarefa', 'Tarefa'), ('sistema', 'Sistema')], max_length=30),
        ),
    ]
