# Generated by Django 4.2.11 on 2026-02-20 12:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleireiro', '0004_rename_duracao_to_duracao_minutos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['nome'], 'verbose_name': 'Profissional (Antigo)', 'verbose_name_plural': 'Profissionais (Antigo)'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_atendimento', 'Em Atendimento'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado'), ('falta', 'Falta')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='profissional',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para bloquear agenda de todos os profissionais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='cabeleireiro.profissional'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
