# Generated by Django 4.2.11 on 2026-03-17 12:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleireiro', '0006_bloqueioagenda_base_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueioagenda',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Bloqueio de Agenda', 'verbose_name_plural': 'Bloqueios de Agenda'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='registro_profissional',
            field=models.CharField(blank=True, help_text='CRM, COREN, etc', max_length=50, null=True, verbose_name='Registro Profissional'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='motivo',
            field=models.CharField(max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='profissional',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para bloquear agenda de todos os profissionais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='cabeleireiro.profissional', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comissão %'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(default='', max_length=100, verbose_name='Especialidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profissional',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('corte', 'Corte'), ('coloracao', 'Coloração'), ('tratamento', 'Tratamento'), ('penteado', 'Penteado'), ('manicure', 'Manicure/Pedicure'), ('barba', 'Barba'), ('depilacao', 'Depilação'), ('maquiagem', 'Maquiagem'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.IntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
