# Generated by Django 4.2.11 on 2026-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0010_add_horario_trabalho_profissional'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='clinica_bel_loja_id_appt_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloqueiohorario',
            name='clinica_bel_loja_id_bloq_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='clinica_bel_loja_id_patient_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='clinica_bel_loja_id_pay_idx',
        ),
        migrations.RemoveIndex(
            model_name='procedure',
            name='clinica_bel_loja_id_proc_idx',
        ),
        migrations.RemoveIndex(
            model_name='professional',
            name='clinica_bel_loja_id_prof_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='clinica_bel_date_eca317_idx',
            old_name='clinica_be_date_st_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='clinica_bel_profess_bd2be6_idx',
            old_name='clinica_be_prof_da_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='clinica_bel_patient_478639_idx',
            old_name='clinica_be_pat_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='clinica_bel_loja_id_102a16_idx',
            old_name='clinica_be_loja_da_idx',
        ),
        migrations.RenameIndex(
            model_name='bloqueiohorario',
            new_name='clinica_bel_data_in_035f02_idx',
            old_name='clinica_be_data_in_idx',
        ),
        migrations.RenameIndex(
            model_name='bloqueiohorario',
            new_name='clinica_bel_profess_901775_idx',
            old_name='clinica_be_prof_di_idx',
        ),
        migrations.RenameIndex(
            model_name='bloqueiohorario',
            new_name='clinica_bel_loja_id_13b4b9_idx',
            old_name='clinica_be_loja_di_idx',
        ),
        migrations.RenameIndex(
            model_name='horariotrabalhoprofissional',
            new_name='clinica_bel_profess_072b43_idx',
            old_name='clinica_be_prof_ds_idx',
        ),
        migrations.RenameIndex(
            model_name='horariotrabalhoprofissional',
            new_name='clinica_bel_loja_id_55761e_idx',
            old_name='clinica_be_loja_pr_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='clinica_bel_status_68ab79_idx',
            old_name='clinica_be_stat_pa_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='clinica_bel_appoint_06a79e_idx',
            old_name='clinica_be_appt_st_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='clinica_bel_loja_id_cb557f_idx',
            old_name='clinica_be_loja_pa_idx',
        ),
        migrations.AlterField(
            model_name='campanhapromocao',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='horariotrabalhoprofissional',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
