# Generated by Django 4.2.11 on 2026-03-17 12:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0015_rename_name_phone_specialty_and_add_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['nome'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['nome'], 'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['nome'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='bloqueiohorario',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='bloqueiohorario',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='horariotrabalhoprofissional',
            name='intervalo_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim intervalo'),
        ),
        migrations.AlterField(
            model_name='horariotrabalhoprofissional',
            name='intervalo_inicio',
            field=models.TimeField(blank=True, help_text='Opcional (ex: almoço)', null=True, verbose_name='Início intervalo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedure',
            name='duracao_minutos',
            field=models.IntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comissão %'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='especialidade',
            field=models.CharField(max_length=100, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='registro_profissional',
            field=models.CharField(blank=True, help_text='CRM, COREN, etc', max_length=50, null=True, verbose_name='Registro Profissional'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
