# Generated by Django 4.2.11 on 2026-05-30 14:43

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_beleza", "0018_procedureprotocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("loja_id", models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro")),
                ("status", models.CharField(choices=[("IN_PROGRESS", "Em Atendimento"), ("COMPLETED", "Concluída"), ("CANCELLED", "Cancelada")], default="IN_PROGRESS", max_length=20, verbose_name="Status")),
                ("data_inicio", models.DateTimeField(blank=True, null=True, verbose_name="Início")),
                ("data_fim", models.DateTimeField(blank=True, null=True, verbose_name="Fim")),
                ("observacoes_gerais", models.TextField(blank=True, default="", verbose_name="Observações gerais")),
                ("protocolo_notas", models.TextField(blank=True, default="", verbose_name="Notas do protocolo")),
                ("valor_consulta", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="consulta", to="clinica_beleza.appointment", verbose_name="Agendamento")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultas", to="clinica_beleza.patient", verbose_name="Cliente")),
                ("procedure", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultas", to="clinica_beleza.procedure", verbose_name="Procedimento")),
                ("professional", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="consultas", to="clinica_beleza.professional", verbose_name="Profissional")),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "db_table": "clinica_beleza_consultas",
                "ordering": ["-data_inicio", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="movimentacaoestoque",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="procedureprotocol",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="produtoestoque",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.CreateModel(
            name="PatientAnamnese",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("loja_id", models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro")),
                ("queixa_principal", models.TextField(blank=True, default="")),
                ("historico_medico", models.TextField(blank=True, default="")),
                ("medicamentos_uso", models.TextField(blank=True, default="")),
                ("alergias", models.TextField(blank=True, default="")),
                ("condicoes_clinicas", models.TextField(blank=True, default="")),
                ("tipo_pele", models.CharField(blank=True, default="", max_length=100)),
                ("pressao_arterial", models.CharField(blank=True, default="", max_length=20)),
                ("peso", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("altura", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="anamnese", to="clinica_beleza.patient", verbose_name="Cliente")),
            ],
            options={
                "verbose_name": "Anamnese do cliente",
                "verbose_name_plural": "Anamneses dos clientes",
                "db_table": "clinica_beleza_anamneses",
            },
        ),
        migrations.CreateModel(
            name="ConsultaEvolucao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("loja_id", models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro")),
                ("descricao", models.TextField(blank=True, default="", verbose_name="Evolução")),
                ("procedimento_realizado", models.TextField(blank=True, default="")),
                ("produtos_utilizados", models.TextField(blank=True, default="")),
                ("orientacoes", models.TextField(blank=True, default="")),
                ("protocolo_snapshot", models.TextField(blank=True, default="", help_text="Texto do protocolo aplicado")),
                ("satisfacao", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consulta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evolucoes", to="clinica_beleza.consulta", verbose_name="Consulta")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evolucoes", to="clinica_beleza.patient", verbose_name="Cliente")),
                ("professional", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="clinica_beleza.professional", verbose_name="Profissional")),
            ],
            options={
                "verbose_name": "Evolução da consulta",
                "verbose_name_plural": "Evoluções das consultas",
                "db_table": "clinica_beleza_consulta_evolucoes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="consulta",
            name="protocol",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="consultas", to="clinica_beleza.procedureprotocol", verbose_name="Protocolo aplicado"),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(fields=["patient", "status"], name="clinica_bel_patient_fd5eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(fields=["loja_id", "status"], name="clinica_bel_loja_id_3a1eb9_idx"),
        ),
    ]
