# Generated by Django 4.2.11 on 2026-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0019_consulta_anamnese_evolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendada'), ('IN_PROGRESS', 'Em Atendimento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
    ]
