# Generated by Django 4.2.11 on 2026-06-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0025_memed_timbrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(blank=True, help_text='Legado: procedimento único. Use appointment_procedures para múltiplos.', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_beleza.procedure', verbose_name='Procedimento principal'),
        ),
        migrations.AlterField(
            model_name='memedtimbrado',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.CreateModel(
            name='AppointmentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio, usa a duração cadastrada do procedimento.', null=True, verbose_name='Duração (min)')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se vazio, usa o preço cadastrado do procedimento.', max_digits=10, null=True, verbose_name='Valor (R$)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_procedures', to='clinica_beleza.appointment', verbose_name='Agendamento')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_beleza.procedure', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento do agendamento',
                'verbose_name_plural': 'Procedimentos do agendamento',
                'db_table': 'clinica_beleza_appointment_procedures',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='appointments_multi', through='clinica_beleza.AppointmentProcedure', to='clinica_beleza.procedure', verbose_name='Procedimentos'),
        ),
    ]
