# Generated by Django 4.2.11 on 2026-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0027_professional_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricaomemed',
            name='pdf_url',
            field=models.URLField(blank=True, default='', help_text='Link para o PDF da prescrição gerado pela Memed.', max_length=500, verbose_name='URL do PDF'),
        ),
    ]
