# Generated by Django 4.2.11 on 2026-06-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0028_prescricao_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('tipo', models.CharField(choices=[('receituario', 'Receituário'), ('pedido_exame', 'Pedido de Exame'), ('atestado', 'Atestado'), ('documento_personalizado', 'Documento Personalizado')], max_length=30, verbose_name='Tipo')),
                ('conteudo', models.TextField(help_text='Texto com placeholders: {{paciente_nome}}, {{data_atual}}, etc.', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='clinica_beleza.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Template de documento',
                'verbose_name_plural': 'Templates de documentos',
                'db_table': 'clinica_beleza_document_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('tipo', models.CharField(choices=[('receituario', 'Receituário'), ('pedido_exame', 'Pedido de Exame'), ('atestado', 'Atestado'), ('documento_personalizado', 'Documento Personalizado')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(help_text='Conteúdo final renderizado do documento.', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinica_beleza.consulta', verbose_name='Consulta')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='clinica_beleza.patient', verbose_name='Paciente')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to='clinica_beleza.professional', verbose_name='Profissional')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica_beleza.documenttemplate', verbose_name='Template usado')),
            ],
            options={
                'verbose_name': 'Documento clínico',
                'verbose_name_plural': 'Documentos clínicos',
                'db_table': 'clinica_beleza_documentos_clinicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
