# Generated by Django 4.2.11 on 2026-06-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_beleza", "0048_patient_foto_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultaassinaturatermo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="despesa",
            new_name="clinica_bel_loja_id_f77ce9_idx",
            old_name="clinica_beleza_despesa_loja_status_idx",
        ),
        migrations.RenameIndex(
            model_name="despesa",
            new_name="clinica_bel_loja_id_068ed5_idx",
            old_name="clinica_beleza_despesa_loja_venc_idx",
        ),
        migrations.RenameIndex(
            model_name="despesa",
            new_name="clinica_bel_loja_id_a04e9e_idx",
            old_name="clinica_beleza_despesa_loja_pag_idx",
        ),
        migrations.AlterField(
            model_name="agendaretornoconfig",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="professional",
            field=models.ForeignKey(blank=True, help_text="Profissional responsável. Pode ser definido ao iniciar a consulta.", null=True, on_delete=django.db.models.deletion.SET_NULL, to="clinica_beleza.professional", verbose_name="Profissional"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(choices=[("CONFIRMED", "Cliente presente"), ("CLIENT_CONFIRMED", "Confirmado pelo WhatsApp"), ("PHONE_CONFIRMED", "Confirmado por ligação"), ("PENDING", "Aguardando confirmação"), ("SCHEDULED", "Aguardando confirmação"), ("IN_PROGRESS", "Em Atendimento"), ("COMPLETED", "Consulta finalizada"), ("CANCELLED", "Cancelado"), ("NO_SHOW", "Faltou")], default="SCHEDULED", max_length=20, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="conteudo_termo_consentimento",
            field=models.TextField(blank=True, default="", verbose_name="Conteúdo do termo de consentimento"),
        ),
        migrations.AlterField(
            model_name="consultaassinaturatermo",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="consultatermoprocedimento",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="nomeagenda",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="pacientefotoacompanhamento",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
        migrations.AlterField(
            model_name="pacientefotoacompanhamento",
            name="origem",
            field=models.CharField(choices=[("qr", "Celular do profissional"), ("painel", "Painel da consulta")], default="qr", max_length=10),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="termo_consentimento",
            field=models.TextField(blank=True, default="", help_text="Use {paciente_nome}, {profissional_nome}, {clinica_nome}, {procedimentos}, {data}.", verbose_name="Termo de consentimento esclarecido"),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="termo_consentimento_ativo",
            field=models.BooleanField(default=False, verbose_name="Exigir termo de consentimento"),
        ),
        migrations.AlterField(
            model_name="produtoestoque",
            name="categoria",
            field=models.CharField(choices=[("injetavel", "Injetável"), ("soroterapia", "Soroterapia"), ("cosmético", "Cosmético"), ("medicamentos", "Medicamentos"), ("descartavel", "Descartável"), ("equipamento", "Equipamento"), ("outro", "Outro")], default="outro", max_length=30, verbose_name="Categoria"),
        ),
        migrations.AlterField(
            model_name="produtoestoque",
            name="procedure",
            field=models.ForeignKey(blank=True, help_text="Vincula o produto ao procedimento (ex.: termo de consentimento).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="produtos_estoque", to="clinica_beleza.procedure", verbose_name="Procedimento vinculado"),
        ),
        migrations.AlterField(
            model_name="retornoprocedimentoregra",
            name="loja_id",
            field=models.IntegerField(db_index=True, help_text="ID da loja proprietária deste registro"),
        ),
    ]
