# Generated by Django 4.2.11 on 2026-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_beleza", "0049_appointment_professional_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="localatendimento",
            name="is_padrao",
            field=models.BooleanField(default=False, help_text="Local pré-selecionado ao criar agendamento.", verbose_name="Padrão"),
        ),
        migrations.AddField(
            model_name="nomeagenda",
            name="is_padrao",
            field=models.BooleanField(default=False, help_text="Nome de agenda pré-selecionado ao criar agendamento.", verbose_name="Padrão"),
        ),
    ]
