# Generated by Django 4.2.11 on 2026-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0051_produto_dias_alerta_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_profissional',
            field=models.BooleanField(default=True, help_text='Se False, é apenas administrador (não aparece na agenda nem recebe agendamentos).', verbose_name='É profissional'),
        ),
    ]
