# Generated by Django 4.2.11 on 2026-07-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_beleza', '0054_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor recebido')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência')], max_length=20, verbose_name='Forma de pagamento')),
                ('status', models.CharField(choices=[('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PAID', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateField(verbose_name='Data do pagamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Parcela de pagamento',
                'verbose_name_plural': 'Parcelas de pagamento',
                'ordering': ['payment_date', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='clinicabelezanfseconfig',
            name='clinica_bel_loja_id_nfse_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultaevolucao',
            name='cb_evolucao_consulta_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentoclinico',
            name='cb_documento_consulta_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='cb_movest_produto_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescricaomemed',
            name='cb_prescricao_patient_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtoestoque',
            name='cb_estoque_validade_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do atendimento. Quando há parcelas, amount pode diferir.', max_digits=10, null=True, verbose_name='Valor total original'),
        ),
        migrations.AlterField(
            model_name='clinicabelezanfseconfig',
            name='provedor_nf',
            field=models.CharField(choices=[('asaas', 'Asaas (Intermediário - Padrão)'), ('issnet', 'ISSNet - Ribeirão Preto (Direto)'), ('nacional', 'API Nacional NFS-e (Direto)'), ('manual', 'Emissão Manual (Sem integração)')], default='asaas', help_text='Sistema usado para emitir notas fiscais de serviço', max_length=20, verbose_name='Provedor de Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('PARTIAL', 'Parcialmente pago'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor cobrado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('PARTIAL', 'Parcialmente pago'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='paymentparcela',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='clinica_beleza.payment', verbose_name='Pagamento'),
        ),
    ]
