# Generated by Django 4.2.11 on 2026-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_beleza", "0055_add_payment_parcela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEBER", "Receber"),
                    ("SCHEDULED", "Agendada"),
                    ("IN_PROGRESS", "Em Atendimento"),
                    ("COMPLETED", "Concluída"),
                    ("CANCELLED", "Cancelada"),
                ],
                default="SCHEDULED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
