# Generated by Django 4.2.11 on 2026-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_beleza", "0059_categoria_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="desconto",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Valor de desconto concedido no atendimento.", max_digits=10, verbose_name="Desconto (R$)"),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="status",
            field=models.CharField(choices=[("PENDING", "Pendente"), ("DRAFT", "Rascunho (consulta)"), ("PAID", "Pago"), ("PARTIAL", "Parcialmente pago"), ("CANCELLED", "Cancelado")], default="PENDING", max_length=20, verbose_name="Status"),
        ),
        migrations.AddIndex(
            model_name="paymentparcela",
            index=models.Index(fields=["payment", "status"], name="cb_parcela_payment_status_idx"),
        ),
    ]
