# Generated by Django 4.2.11 on 2026-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0003_vendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
    ]
