# Generated by Django 4.2.11 on 2026-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0004_cliente_loja_id_lead_loja_id_pipeline_loja_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Indica se é o administrador da loja', verbose_name='É Administrador'),
        ),
    ]
