# Generated by Django 4.2.11 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0004_ensure_google_event_id_in_tenant_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duração estimada da atividade em minutos'),
        ),
    ]
