# Generated by Django 4.2.11 on 2026-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0018_alter_field_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmconfig',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
    ]
