# Generated by Django - Add contato field to Lead model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0029_add_categoria_codigo_produto_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contato',
            field=models.ForeignKey(
                blank=True,
                help_text='Contato específico vinculado ao lead',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads',
                to='crm_vendas.contato'
            ),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['loja_id', 'contato'], name='crm_lead_loja_contato_idx'),
        ),
    ]
