# Generated by Django 4.2.11 on 2026-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0047_certificado_binary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produtoservico',
            name='crm_ps_unique_codigo_loja',
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='categoriaprodutoservico',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='contratotemplate',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='crmconfig',
            name='issnet_certificado',
            field=models.BinaryField(blank=True, help_text='Conteúdo binário do arquivo .pfx (salvo no banco, não em disco)', null=True, verbose_name='Certificado Digital A1'),
        ),
        migrations.AlterField(
            model_name='crmconfig',
            name='issnet_certificado_nome',
            field=models.CharField(blank=True, help_text='Nome original do arquivo enviado', max_length=255, verbose_name='Nome do arquivo .pfx'),
        ),
        migrations.AlterField(
            model_name='propostatemplate',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AddConstraint(
            model_name='produtoservico',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__isnull', False), models.Q(('codigo', ''), _negated=True)), fields=('loja_id', 'codigo'), name='crm_ps_unique_codigo_loja'),
        ),
    ]
