# Generated by Django 4.2.11 on 2026-05-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0056_atividade_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='conta',
            field=models.ForeignKey(blank=True, help_text='Conta (empresa) vinculada a esta atividade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='crm_vendas.conta'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['loja_id', 'conta'], name='crm_ativ_loja_conta_idx'),
        ),
    ]
