# Generated by Django 4.2.11 on 2026-07-01 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0063_assinatura_digital_link_enviado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFinanceiroCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo financeiro CRM',
                'verbose_name_plural': 'Grupos financeiros CRM',
                'db_table': 'crm_financeiro_grupo',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiroCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('comissao_venda', 'Comissão de venda')], default='manual', max_length=20, verbose_name='Origem')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=12, verbose_name='Status')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='crm_vendas.grupofinanceirocrm', verbose_name='Grupo')),
                ('oportunidade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamento_comissao', to='crm_vendas.oportunidade', verbose_name='Oportunidade (comissão)')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='crm_vendas.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro CRM',
                'verbose_name_plural': 'Lançamentos financeiros CRM',
                'db_table': 'crm_financeiro_lancamento',
                'ordering': ['-data_vencimento', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grupofinanceirocrm',
            index=models.Index(fields=['loja_id', 'tipo', 'is_active'], name='crm_finance_loja_id_bf6f65_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceirocrm',
            index=models.Index(fields=['loja_id', 'tipo', 'status'], name='crm_finance_loja_id_6d486c_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceirocrm',
            index=models.Index(fields=['loja_id', 'vendedor_id', 'tipo'], name='crm_finance_loja_id_952ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceirocrm',
            index=models.Index(fields=['loja_id', 'data_vencimento'], name='crm_finance_loja_id_7ac72e_idx'),
        ),
    ]
