# Generated by Django 4.2.11 on 2026-07-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0064_financeiro_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorrenciaFinanceiroCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('frequencia', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=12, verbose_name='Frequência')),
                ('proximo_vencimento', models.DateField(verbose_name='Próximo vencimento')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Encerrar em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias', to='crm_vendas.grupofinanceirocrm', verbose_name='Grupo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias_financeiras', to='crm_vendas.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Recorrência financeira CRM',
                'verbose_name_plural': 'Recorrências financeiras CRM',
                'db_table': 'crm_financeiro_recorrencia',
                'ordering': ['tipo', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='lancamentofinanceirocrm',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_gerados', to='crm_vendas.recorrenciafinanceirocrm', verbose_name='Recorrência'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceirocrm',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('comissao_venda', 'Comissão de venda'), ('recorrencia', 'Recorrência automática')], default='manual', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddIndex(
            model_name='recorrenciafinanceirocrm',
            index=models.Index(fields=['loja_id', 'is_active', 'proximo_vencimento'], name='crm_finance_loja_id_recorr_idx'),
        ),
        migrations.AddIndex(
            model_name='recorrenciafinanceirocrm',
            index=models.Index(fields=['loja_id', 'vendedor_id', 'tipo'], name='crm_finance_loja_id_rec_v_idx'),
        ),
    ]
