# Generated by Django 4.2.11 on 2026-07-06 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0069_oportunidade_negociacao_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['nome'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RenameIndex(
            model_name='recorrenciafinanceirocrm',
            new_name='crm_finance_loja_id_decdc1_idx',
            old_name='crm_finance_loja_id_recorr_idx',
        ),
        migrations.RenameIndex(
            model_name='recorrenciafinanceirocrm',
            new_name='crm_finance_loja_id_0ebfd3_idx',
            old_name='crm_finance_loja_id_rec_v_idx',
        ),
        migrations.AlterField(
            model_name='oportunidadenota',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no Asaas (cus_xxxxx)', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='asaas_payment_id',
            field=models.CharField(blank=True, help_text='ID da cobrança no Asaas (pay_xxxxx)', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='boleto_url',
            field=models.URLField(blank=True, help_text='URL do boleto para pagamento'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='dados_oportunidades',
            field=models.JSONField(default=list, help_text='Lista de oportunidades incluídas no relatório (snapshot)'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='empresa_prestadora',
            field=models.ForeignKey(help_text='Empresa prestadora que receberá o relatório para aprovação', on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_comissao', to='crm_vendas.conta'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='numero',
            field=models.CharField(blank=True, help_text='Número sequencial do relatório (ex: RC-2024-001)', max_length=20),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='periodo_descricao',
            field=models.CharField(blank=True, help_text='Descrição legível do período (ex: Maio/2024)', max_length=100),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='periodo_fim',
            field=models.DateField(help_text='Data de fim do período'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='periodo_inicio',
            field=models.DateField(help_text='Data de início do período'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='quantidade_vendas',
            field=models.IntegerField(default=0, help_text='Número de vendas fechadas no período'),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='titulo',
            field=models.CharField(help_text='Título descritivo (ex: Comissões Maio/2024 — Felix Representações)', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='token_empresa',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token para a empresa prestadora aprovar/reprovar', unique=True),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='token_vendedor',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token para o vendedor assinar', unique=True),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='valor_total_comissao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total da comissão a pagar', max_digits=12),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='valor_total_vendas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soma total das vendas no período', max_digits=12),
        ),
        migrations.AlterField(
            model_name='relatoriocomissao',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor que assina o relatório após aprovação da empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_comissao', to='crm_vendas.vendedor'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceirocrm',
            index=models.Index(fields=['loja_id', 'data_pagamento'], name='crm_lanc_loja_dtpag_idx'),
        ),
    ]
