# Generated by Django 4.2.11 on 2026-01-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(max_length=100, unique=True, verbose_name='ID no Asaas')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Referência Externa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos do Asaas')),
            ],
            options={
                'verbose_name': 'Cliente Asaas',
                'verbose_name_plural': 'Clientes Asaas',
                'db_table': 'asaas_customer',
            },
        ),
        migrations.CreateModel(
            name='AsaasPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(max_length=100, unique=True, verbose_name='ID no Asaas')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Referência Externa')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'PIX'), ('UNDEFINED', 'Não definido')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('RECEIVED', 'Recebida'), ('CONFIRMED', 'Pagamento confirmado'), ('OVERDUE', 'Vencida'), ('REFUNDED', 'Estornada'), ('RECEIVED_IN_CASH', 'Recebida à vista'), ('REFUND_REQUESTED', 'Estorno solicitado'), ('REFUND_IN_PROGRESS', 'Estorno em processamento'), ('CHARGEBACK_REQUESTED', 'Chargeback solicitado'), ('CHARGEBACK_DISPUTE', 'Em disputa de chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando reversão do chargeback'), ('DUNNING_REQUESTED', 'Cobrança solicitada'), ('DUNNING_RECEIVED', 'Cobrança recebida'), ('AWAITING_RISK_ANALYSIS', 'Aguardando análise')], max_length=30, verbose_name='Status')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('invoice_url', models.URLField(blank=True, verbose_name='URL da Fatura')),
                ('bank_slip_url', models.URLField(blank=True, verbose_name='URL do Boleto')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos do Asaas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asaas_integration.asaascustomer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cobrança Asaas',
                'verbose_name_plural': 'Cobranças Asaas',
                'db_table': 'asaas_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LojaAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_slug', models.CharField(max_length=100, unique=True, verbose_name='Slug da Loja')),
                ('loja_nome', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('plano_nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('plano_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Plano')),
                ('ativa', models.BooleanField(default=True, verbose_name='Assinatura Ativa')),
                ('data_ativacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Ativação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asaas_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asaas_integration.asaascustomer', verbose_name='Cliente Asaas')),
                ('current_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_subscription', to='asaas_integration.asaaspayment', verbose_name='Pagamento Atual')),
            ],
            options={
                'verbose_name': 'Assinatura da Loja',
                'verbose_name_plural': 'Assinaturas das Lojas',
                'db_table': 'loja_assinatura',
                'ordering': ['-created_at'],
            },
        ),
    ]
