# Generated by Django 4.2.11 on 2026-01-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asaaspayment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
    ]
