# Generated by Django 4.2.11 on 2026-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_integration', '0003_alter_asaaspayment_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='config', max_length=10, unique=True)),
                ('api_key', models.TextField(verbose_name='Chave da API Asaas')),
                ('sandbox', models.BooleanField(default=True, verbose_name='Ambiente Sandbox')),
                ('enabled', models.BooleanField(default=False, verbose_name='Integração Habilitada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
            ],
            options={
                'verbose_name': 'Configuração Asaas',
                'verbose_name_plural': 'Configurações Asaas',
                'db_table': 'asaas_config',
            },
        ),
    ]
