# Generated by Django 4.2.11 on 2026-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Indica se é o administrador da loja', verbose_name='É Administrador'),
        ),
    ]
