# Generated by Django 4.2.11 on 2026-01-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_add_funcionario_loja_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=200)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_minima', models.DecimalField(decimal_places=3, default=0, help_text='Alerta quando estoque ficar abaixo', max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'db_table': 'restaurante_estoque_itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'restaurante_fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('numero', models.CharField(max_length=30, verbose_name='Número da NF')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to=restaurante.models.nfe_upload_path, verbose_name='Arquivo XML da NF-e')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aplicado_estoque', models.BooleanField(default=False, help_text='Se os itens da NF já foram lançados no estoque', verbose_name='Aplicado ao estoque')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='restaurante.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'db_table': 'restaurante_notas_fiscais_entrada',
                'ordering': ['-data_entrada', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estoque_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='restaurante.estoqueitem')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='restaurante.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'db_table': 'restaurante_movimentos_estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurante.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Item da NF',
                'verbose_name_plural': 'Itens da NF',
                'db_table': 'restaurante_itens_nf_entrada',
            },
        ),
    ]
