# Generated by Django 4.2.11 on 2026-01-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_add_fornecedor_nfe_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPesoBalança',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso (kg)')),
                ('adicionar_ao_estoque', models.BooleanField(default=True, help_text='Se True, gera entrada no estoque com essa quantidade (kg)')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estoque_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_peso', to='restaurante.estoqueitem')),
            ],
            options={
                'verbose_name': 'Registro de Peso (Balança)',
                'verbose_name_plural': 'Registros de Peso (Balança)',
                'db_table': 'restaurante_registros_peso_balanca',
                'ordering': ['-created_at'],
            },
        ),
    ]
