# Generated by Django 4.2.11 on 2026-01-21 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_estetica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do protocolo')),
                ('preparacao', models.TextField(help_text='Preparação do cliente e ambiente')),
                ('execucao', models.TextField(help_text='Passos de execução do procedimento')),
                ('pos_procedimento', models.TextField(help_text='Cuidados pós-procedimento')),
                ('tempo_estimado', models.IntegerField(help_text='Tempo estimado em minutos')),
                ('materiais_necessarios', models.TextField(help_text='Lista de materiais necessários')),
                ('contraindicacoes', models.TextField(blank=True, help_text='Contraindicações do procedimento')),
                ('cuidados_especiais', models.TextField(blank=True, help_text='Cuidados especiais')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='clinica_estetica.procedimento')),
            ],
            options={
                'verbose_name': 'Protocolo de Procedimento',
                'verbose_name_plural': 'Protocolos de Procedimentos',
                'db_table': 'clinica_protocolos',
                'ordering': ['procedimento__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('intervalo_inicio', models.TimeField(blank=True, help_text='Início do intervalo de almoço', null=True)),
                ('intervalo_fim', models.TimeField(blank=True, help_text='Fim do intervalo de almoço', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'db_table': 'clinica_horarios_funcionamento',
                'ordering': ['dia_semana'],
                'unique_together': {('dia_semana',)},
            },
        ),
        migrations.CreateModel(
            name='EvolucaoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evolucao', models.DateTimeField(auto_now_add=True)),
                ('queixa_principal', models.TextField(help_text='Queixa principal do paciente')),
                ('historico_medico', models.TextField(blank=True, help_text='Histórico médico relevante')),
                ('medicamentos_uso', models.TextField(blank=True, help_text='Medicamentos em uso')),
                ('alergias', models.TextField(blank=True, help_text='Alergias conhecidas')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura em metros', max_digits=4, null=True)),
                ('pressao_arterial', models.CharField(blank=True, help_text='Ex: 120x80', max_length=20)),
                ('tipo_pele', models.CharField(blank=True, help_text='Tipo de pele', max_length=50)),
                ('condicoes_pele', models.TextField(blank=True, help_text='Condições observadas na pele')),
                ('areas_tratamento', models.TextField(help_text='Áreas a serem tratadas')),
                ('procedimento_realizado', models.TextField(help_text='Descrição do procedimento realizado')),
                ('produtos_utilizados', models.TextField(blank=True, help_text='Produtos utilizados')),
                ('parametros_equipamento', models.TextField(blank=True, help_text='Parâmetros de equipamentos utilizados')),
                ('reacao_imediata', models.TextField(blank=True, help_text='Reação imediata do paciente')),
                ('orientacoes_dadas', models.TextField(blank=True, help_text='Orientações dadas ao paciente')),
                ('proxima_sessao', models.DateField(blank=True, help_text='Data sugerida para próxima sessão', null=True)),
                ('fotos_antes', models.TextField(blank=True, help_text='URLs das fotos antes do procedimento')),
                ('fotos_depois', models.TextField(blank=True, help_text='URLs das fotos depois do procedimento')),
                ('satisfacao_paciente', models.IntegerField(blank=True, help_text='Satisfação do paciente (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='clinica_estetica.agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='clinica_estetica.cliente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica_estetica.profissional')),
            ],
            options={
                'verbose_name': 'Evolução do Paciente',
                'verbose_name_plural': 'Evoluções dos Pacientes',
                'db_table': 'clinica_evolucoes',
                'ordering': ['-data_evolucao'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('ferias', 'Férias'), ('manutencao', 'Manutenção'), ('evento', 'Evento'), ('outros', 'Outros')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horario_inicio', models.TimeField(blank=True, help_text='Se não informado, bloqueia o dia todo', null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(blank=True, help_text='Se não informado, bloqueia para todos', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_estetica.profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'db_table': 'clinica_bloqueios_agenda',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AnamnesesTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('perguntas', models.JSONField(default=list, help_text='Lista de perguntas para anamnese')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_templates', to='clinica_estetica.procedimento')),
            ],
            options={
                'verbose_name': 'Template de Anamnese',
                'verbose_name_plural': 'Templates de Anamnese',
                'db_table': 'clinica_anamneses_templates',
                'ordering': ['procedimento__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField(default=dict, help_text='Respostas do paciente às perguntas da anamnese')),
                ('assinatura_digital', models.TextField(blank=True, help_text='Assinatura digital do paciente')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clinica_estetica.agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='clinica_estetica.cliente')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_estetica.anamnesestemplate')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'db_table': 'clinica_anamneses',
                'ordering': ['-created_at'],
            },
        ),
    ]
