# Generated by Django 4.2.11 on 2026-01-22 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica_estetica', '0003_consulta_evolucaopaciente_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuário do sistema vinculado ao funcionário', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinica_funcionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
