# Generated by Django 4.2.11 on 2026-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_estetica', '0004_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evolucaopaciente',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimento',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocoloprocedimento',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID da loja proprietária deste registro'),
            preserve_default=False,
        ),
    ]
