# Generated by Django 4.2.11 on 2026-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_estetica', '0005_agendamento_loja_id_cliente_loja_id_consulta_loja_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Indica se é o administrador da loja'),
        ),
    ]
