# Generated by Django 4.2.11 on 2026-02-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_estetica', '0007_historicologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'db_table': 'clinica_categorias_financeiras',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('cheque', 'Cheque'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('anexo', models.CharField(blank=True, help_text='URL do anexo (nota fiscal, recibo, etc)', max_length=500, null=True, verbose_name='Anexo')),
                ('is_recorrente', models.BooleanField(default=False, verbose_name='É Recorrente')),
                ('recorrencia_tipo', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, null=True, verbose_name='Tipo de Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'clinica_transacoes',
                'ordering': ['-data_vencimento', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='historicologin',
            new_name='clinica_his_loja_id_9b162f_idx',
            old_name='clinica_his_loja_id_f8c9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='historicologin',
            new_name='clinica_his_usuario_2e896a_idx',
            old_name='clinica_his_usuario_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='historicologin',
            new_name='clinica_his_acao_1438a2_idx',
            old_name='clinica_his_acao_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='loja_id',
            field=models.IntegerField(db_index=True, help_text='ID da loja proprietária deste registro'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='agendamento',
            field=models.ForeignKey(blank=True, help_text='Agendamento relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica_estetica.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica_estetica.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente relacionado (para receitas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica_estetica.cliente', verbose_name='Cliente'),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['loja_id', 'tipo'], name='clinica_cat_loja_id_5dc7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['loja_id', 'is_active'], name='clinica_cat_loja_id_a0b4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['loja_id', 'tipo', 'status'], name='clinica_tra_loja_id_c55cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['loja_id', 'data_vencimento'], name='clinica_tra_loja_id_b36424_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['loja_id', 'data_pagamento'], name='clinica_tra_loja_id_32d674_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['loja_id', 'categoria'], name='clinica_tra_loja_id_b4bd87_idx'),
        ),
    ]
