# Generated by Django 4.2.11 on 2026-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_estetica', '0009_alter_cliente_email_alter_profissional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueioagenda',
            name='loja_id',
            field=models.IntegerField(db_index=True, default=0, help_text='ID da loja (isolamento multi-tenant)'),
            preserve_default=False,
        ),
    ]
